# Generated by Django 4.1.7 on 2023-02-28 16:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_taskmodel_delete_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'etat',
            },
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='etat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todoapp.etatmodel'),
        ),
    ]
