# Generated by Django 4.1.7 on 2023-03-08 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_categorymodel_taskmodel_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etatmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todoapp.categorymodel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='deadline',
            field=models.DateField(default=datetime.date(2023, 3, 8)),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='etat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todoapp.etatmodel'),
        ),
        migrations.AlterModelTable(
            name='etatmodel',
            table='etats',
        ),
    ]
