# Generated by Django 4.1.7 on 2023-03-09 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_alter_categorymodel_id_alter_etatmodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todoapp.categorymodel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='deadline',
            field=models.DateField(default=datetime.date(2023, 3, 9)),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='etat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapp.etatmodel'),
        ),
    ]
